import { Component, Input } from '@angular/core';
import sdk from '@stackblitz/sdk';

@Component({
  selector: 'app-open-stackblitz',
  template: `
    <button
      class="rounded-md border-2 border-black h-[48px] px-4 bg-white hover:bg-black hover:text-white transition-all ease-in duration-300"
      (click)="open()"
    >
      Open in Stackblitz
    </button>
  `,
  standalone: true,
})
export class OpenStackblitzComponent {
  @Input({ required: true }) template = '';

  open(): void {
    sdk.openProject(
      {
        files: {
          'index.html': this.template,
        },
        template: 'html',
        title: `My generated template!`,
        description: `This is an template generated by angular + gemini!`,
      },
      {
        newWindow: true,
      },
    );
  }
}
